spring:
  datasource:
    url: jdbc:mysql://dna03.com:3306/comments?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: CommentX
  banner:
    location: banner.txt
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*
  type-aliases-package: icu.chenz.comments.entity
management:
  endpoints:
    web:
      exposure:
        exclude: '*'
comments:
  jwt:
    expire-time: 86400001